import { MyInfoComponentsV4 } from "src/types";

export interface FakeProfile {
	id: string;
	name: ProfileArchetype;
	generate: (profileName?: string) => MyInfoComponentsV4.Schemas.Person;
}

/**
 * Used in MyInfo.Fake.Helper.getPersonData to get a archetype person
 */
export enum ProfileArchetype {
	MR_PRESCHOOL_REGISTRATION = "Mr SG Father with preschool children",
	MRS_PRESCHOOL_REGISTRATION = "Mrs SG Mother with preschool children",
	// Sponsored Children profiles
	MR_SG_FATHER_ONLY_SPONSORED = "Mr SG Father with only sponsored children",
	MR_SG_FATHER_NORMAL_CHILDREN = "Mr SG Father with only normal children",
	MS_SG_MOTHER_HAVING_BOTH_CHILDREN = "Ms SG Mother having normal and sponsored children",
	// Regular Profiles
	MR_PR_DADDY_ONE_CHILD = "Mr PR Daddy with One Child and Expired Passport",
	MR_PR_DADDY_PERFECT = "Mr PR Daddy Perfect",
	MR_SG_DADDY_CHILD_IS_OLD = "Mr SG with 1 old child",
	MR_SG_DADDY_CHILD_NONE = "Mr SG with no children",
	MR_SG_DADDY_LONG_NAMES = "Mr SG daddy with long names",
	MR_SG_DADDY_MANY_CHILDREN = "Mr SG with many children",
	MR_SG_DADDY_MISSING_FIELDS = "Mr SG Daddy Missing Fields",
	MR_SG_DADDY_MISSING_UNEDITABLE_FIELDS = "Mr SG Daddy Missing Uneditable Fields",
	MR_SG_DADDY_PERFECT = "Mr SG Daddy Perfect",
	MR_SG_PRESCHOOL_CHILDREN = "Mr SG Preschool Children",
	MRS_MY_MOMMY_PERFECT = "Mrs MY Mommy Perfect",
	MRS_SG_MOMMY_PERFECT = "Mrs SG Mommy Perfect",
	MR_MY_DADDY_PERFECT = "Mr MY Daddy Perfect",
	MR_SG_UNCLE_NON_MG = "Mr SG Uncle Non MG",
	MR_SG_UNCLE_MG_ALL_OK = "Mr SG Uncle MG All Ok",
	MR_SG_UNCLE_MG_NEED_ADDR_UPDATE = "Mr SG Uncle MG needs address update",
	MR_SG_UNCLE_MG_NEED_MEDISAVE = "Mr SG Uncle MG need medisave",
	MR_SG_UNCLE_MG_CALL_RECEIVE = "Mr SG Uncle MG call to receive",
	MR_SG_UNCLE_MG_OPT_OUT = "Mr SG Uncle MG Opt-out",
	MR_SG_UNCLE_MG_NIL_STATUS = "Mr SG Uncle MG nil status",
	MR_SG_UNCLE_NON_PG = "Mr SG Uncle Non PG",
	MR_SG_UNCLE_PG_ALL_OK = "Mr SG Uncle PG All Ok",
	MR_SG_UNCLE_PG_NEED_ADDR_UPDATE = "Mr SG Uncle PG needs address update",
	MR_SG_UNCLE_PG_NEED_MEDISAVE = "Mr SG Uncle PG need medisave",
	MR_SG_UNCLE_PG_CALL_RECEIVE = "Mr SG Uncle PG call to receive",
	MR_SG_UNCLE_PG_OPT_OUT = "Mr SG Uncle PG Opt-out",
	MR_SG_UNCLE_PG_NIL_STATUS = "Mr SG Uncle PG nil status",
	MR_SG_UNCLE_NON_BENEFITS = "Mr SG Uncle Non Benefits",
	MR_SG_UNCLE_GST_SCENARIO_1A = "Mr GSTV Uncle 1a no exclusion got signup got $",
	MR_SG_UNCLE_GST_SCENARIO_1A2 = "Mr GSTV Uncle 1a2 no exclusion got signup got gst regular only",
	MR_SG_UNCLE_GST_SCENARIO_1B = "Mr GSTV Uncle 1b no exclusion got signup no $",
	MR_SG_UNCLE_GST_SCENARIO_2A = "Mr GSTV Uncle 2a no exclusion no signup got $",
	MR_SG_UNCLE_GST_SCENARIO_2A2 = "Mr GSTV Uncle 2a2 no exclusion no signup got gst bicentennial only",
	MR_SG_UNCLE_GST_SCENARIO_2A3 = "Mr GSTV Uncle 2a3 no exclusion no signup got gst regular & medisave only",
	MR_SG_UNCLE_GST_SCENARIO_2B = "Mr GSTV Uncle 2b no exclusion no signup no $",
	MR_SG_UNCLE_GST_SCENARIO_3 = "Mr GSTV Uncle 3 got exclusion got signup got $",
	MR_SG_UNCLE_GST_SCENARIO_4 = "Mr GSTV Uncle 4 got exclusion no signup got $",
	MR_MY_DAD_JOBLESS = "Mr MY Dad Jobless",
	MRS_MY_MOM_JOBLESS = "Mrs MY Mom Jobless",
	MR_SG_JOBLESS = "Mr SG Jobless",
	MR_SG_FROM_BEDOK = "Mr SG From Bedok",
	MR_SG_NO_LOCAL_ADDRESS = "Mr SG No Local Address",
	MR_SG_LANDED_ADDRESS = "Mr SG Landed Address",
	MR_SG_NO_ADDRESS = "Mr SG No Address",
	MR_PR_NO_LOCAL_ADDRESS = "Mr PR No Local Address",
	MR_JAPANESE_NO_ADDRESS_OBJECT = "Mr Japanese No Address Object",
	MR_JAPANESE_ADDRESS_BLANK = "Mr Japanese Address Blank",
	MR_PR_JOBLESS = "Mr PR Jobless",
	MR_SG_DADDY_TWO_DECEASED_CHILD = "My SG Daddy with Two Deceased Child",
	MR_SG_FRESH_GRAD_YOUNG_PARENT = "Mr SG Fresh Grad, Young Parent",
	MRS_PR_HDB_OWNER_WORKING_ADULT_MID_CAREER_PMETS = "Mrs PR HDB Owner, Working adults (Mid-career PMETs)",
	MR_SG_UNCLE_RETIREE = "Mr SG Uncle Retiree",
	MR_SG_TEENAGER_17 = "Mr SG Teenager 17",
	MS_SG_TEENAGER_17 = "Ms SG Teenager 17",
	// Dedicated for iOS app Reviewer
	MR_APP_REVIEWER = "Mr App Reviewer",
	// For BRV2 ICA UAT
	MR_ICA_SG_DADDY_SPOUSE_SCENARIO_1 = "Mr SG Daddy Spouse Applicant Scenario One No Audit Required",
	MRS_ICA_SG_MOMMY_MAIN_SCENARIO_1 = "Mrs SG Mommy Main Applicant Scenario One No Audit Required",
	MR_ICA_PR_DADDY_SPOUSE_SCENARIO_2 = "Mr PR Daddy Spouse Applicant Scenario Two MAR",
	MRS_ICA_SG_MOMMY_MAIN_SCENARIO_2 = "Mrs SG Mommy Main Applicant Scenario Two MAR",
	MR_ICA_SG_DADDY_MAIN_SCENARIO_3 = "Mr SG Daddy Main Applicant Scenario Three MAR",
	MRS_ICA_PR_MOMMY_SPOUSE_SCENARIO_3 = "Mrs PR Mommy Spouse Applicant Scenario Three MAR",
	MR_ICA_FP_DADDY_MAIN_SCENARIO_4 = "Mr FP Daddy Main Applicant Scenario Four LBI",
	MRS_ICA_PR_MOMMY_SPOUSE_SCENARIO_4 = "Mrs PR Mommy Spouse Applicant Scenario Four LBI",
	MR_ICA_SC_DADDY_MAIN_SCENARIO_5 = "Mr SG Daddy Main Applicant Scenario Five MLB",
	MRS_ICA_SC_MOMMY_SPOUSE_SCENARIO_5 = "Mrs SG Mommy Spouse Applicant Scenario Five MLB",
	MRS_ICA_PR_MOMMY_MAIN_SCENARIO_6 = "Mrs PR Mommy Main Applicant Scenario Six IDE",
	MR_ICA_SC_DADDY_MAIN_SCENARIO_7 = "Mr SG Daddy Spouse Applicant Scenario Seven IML",
	MRS_ICA_SC_SINGLE_MOMMY_MAIN_SCENARIO_8 = "Mrs SG Single Mommy Main Applicant Scenario Eight",
	// For Book Fac UAT
	MR_CCK_RESIDENT_1 = "Mr CCK Resident 1",
	MS_CCK_RESIDENT_2 = "Ms CCK Resident 2",
	MR_CCK_RESIDENT_3 = "Mr CCK Resident 3",
	MR_CCK_RESIDENT_4 = "Mr CCK Resident 4",
	MS_CCK_RESIDENT_5 = "Ms CCK Resident 5",
	MR_CCK_RESIDENT_6 = "Mr CCK Resident 6",
	MS_HBP_RESIDENT_1 = "Ms HBP Resident 1",
	MR_HBP_RESIDENT_2 = "Mr HBP Resident 2",
	MS_HBP_RESIDENT_3 = "Ms HBP Resident 3",
	MS_HBP_RESIDENT_4 = "Ms HBP Resident 4",
	MR_HBP_RESIDENT_5 = "Mr HBP Resident 5",
	MS_HBP_RESIDENT_6 = "Ms HBP Resident 6",
	MR_MP_RESIDENT_1 = "Mr MP Resident 1",
	MS_MP_RESIDENT_2 = "Ms MP Resident 2",
	MR_MP_RESIDENT_3 = "Mr MP Resident 3",
	MR_MP_RESIDENT_4 = "Mr MP Resident 4",
	MS_MP_RESIDENT_5 = "Ms MP Resident 5",
	MR_MP_RESIDENT_6 = "Mr MP Resident 6",
	MS_NS_RESIDENT_1 = "Ms NS Resident 1",
	MR_NS_RESIDENT_2 = "Mr NS Resident 2",
	MR_NS_RESIDENT_3 = "Mr NS Resident 3",
	MS_NS_RESIDENT_4 = "Ms NS Resident 4",
	MR_NS_RESIDENT_5 = "Mr NS Resident 5",
	MS_NS_RESIDENT_6 = "Ms NS Resident 6",
	MS_PRPG_RESIDENT_1 = "Ms PRPG Resident 1",
	MS_PRPG_RESIDENT_2 = "Ms PRPG Resident 2",
	MR_PRPG_RESIDENT_3 = "Mr PRPG Resident 3",
	MR_PRPG_RESIDENT_4 = "Mr PRPG Resident 4",
	MR_PRPG_RESIDENT_5 = "Mr PRPG Resident 5",
	MR_PRPG_RESIDENT_6 = "Mr PRPG Resident 6",
	MR_PUTC_RESIDENT = "Mr PUTC Resident",
	MR_JYTC_RESIDENT = "Mr JYTC Resident",
	MR_TETC_RESIDENT = "Mr TETC Resident",
	MR_WATC_RESIDENT = "Mr WATC Resident",
	MR_JETC_RESIDENT = "Mr JETC Resident",
	MR_MPTC_RESIDENT = "Mr MPTC Resident",
}
