import * as moment from "moment";
import { myInfoDomain } from "../../domain";
export declare const formatDateToString: (date?: moment.Moment) => string;
export declare const preschoolEligibleChild_IC: myInfoDomain.Components.Schemas.Childrenbirthrecords;
export declare const preschoolEligibleChild_N2: myInfoDomain.Components.Schemas.Childrenbirthrecords;
export declare const preschoolEligibleChild_PG: myInfoDomain.Components.Schemas.Childrenbirthrecords;
export declare const preschoolEligibleChild_N1: myInfoDomain.Components.Schemas.Childrenbirthrecords;
export declare const preschoolEligibleChild_K1: myInfoDomain.Components.Schemas.Childrenbirthrecords;
export declare const preschoolEligibleChild_K2: myInfoDomain.Components.Schemas.Childrenbirthrecords;
export declare const preschoolEligibleChild2_N1: myInfoDomain.Components.Schemas.Childrenbirthrecords;
export declare const preschoolEligibleChild2_IC: myInfoDomain.Components.Schemas.Childrenbirthrecords;
export declare const preschoolEligibleChild2_K1: myInfoDomain.Components.Schemas.Childrenbirthrecords;
export declare const preschoolEligibleChild2_N2: myInfoDomain.Components.Schemas.Childrenbirthrecords;
export declare const preschoolEligibleChild2_PG: myInfoDomain.Components.Schemas.Childrenbirthrecords;
export declare const preschoolEligibleChild2_K2: myInfoDomain.Components.Schemas.Childrenbirthrecords;
export declare const preschoolIneligibleChild1: myInfoDomain.Components.Schemas.Childrenbirthrecords;
export declare const preschoolIneligibleChild2: myInfoDomain.Components.Schemas.Childrenbirthrecords;
export declare const ChildrenRecords: {
    childYoungest: myInfoDomain.Components.Schemas.Childrenbirthrecords;
    child1MonthOld: myInfoDomain.Components.Schemas.Childrenbirthrecords;
    child2MonthsOld: myInfoDomain.Components.Schemas.Childrenbirthrecords;
    childMiddle1: myInfoDomain.Components.Schemas.Childrenbirthrecords;
    childMiddle2: myInfoDomain.Components.Schemas.Childrenbirthrecords;
    childMiddle3: myInfoDomain.Components.Schemas.Childrenbirthrecords;
    childMiddle4: myInfoDomain.Components.Schemas.Childrenbirthrecords;
    childMiddle5: myInfoDomain.Components.Schemas.Childrenbirthrecords;
    childSuperOld: myInfoDomain.Components.Schemas.Childrenbirthrecords;
    child6YearsOld: myInfoDomain.Components.Schemas.Childrenbirthrecords;
    child7YearsOld: myInfoDomain.Components.Schemas.Childrenbirthrecords;
    childDeceased1: myInfoDomain.Components.Schemas.Childrenbirthrecords;
    childDeceased2: myInfoDomain.Components.Schemas.Childrenbirthrecords;
};
//# sourceMappingURL=childbirthRecords.d.ts.map